View(airquality)
#A(histogram)
hist(airquality$Wind,main = "Wind")
#B(adding color)
hist(airquality$Wind,main = "Wind",col="pink",border = "green")
#C(remove axis add label)
hist(airquality$Wind,main = "Wind",axes=FALSE,xlab="wind",ylab = "frequency")
#D(changing axis limit)
hist(airquality$Wind,main = "Wind",xlab="wind",ylab = "frequency",xlim = c(0,25),ylim = c(0,50))
#E(density curve)
hist(airquality$Wind, main = "Histogram of Wind Speed", xlab = "Wind (mph)", ylab = "Density", col = "lightgreen", border = "black", freq = FALSE)
lines(density(na.omit(airquality$Wind)), col = "blue", lwd = 2)
